server:
  port: 8090

spring:
  application:
    name: CLIENT
  datasource:
    url: jdbc:mysql://localhost:3306/zz
    username: root
    password: P@$$w0rd
  jpa:
    hibernate:
      ddl-auto: update